### ISSUE TITLE
incompatiple with other mod

### ISSUE THREAD

**Issue by MisatoAino** [Mrbysco/Armor-Poser#10]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Forge 47.4.47

### Minecraft version

1.20.1

### Mod version

1.20.1-2.1.1

### Java version

ver.  8 Update 381

### Issue Description

game crash when opening armor stand GUI.

i think the mod is incompatible with this mod.
https://www.curseforge.com/minecraft/mc-mods/curious-armor-stands

maybe it can be fixed. if not so maybe you should povide the information in the mod information overview

i put a copy of the crash report in the additional informations fpr you

### Additional Information

[message.txt](https://github.com/Mrbysco/Armor-Poser/files/12861242/message.txt)

**Comment by Mrbysco** [comment]
There isn't much I can do about it, it feels like there's a null check missing in the layer renderer of Curious Armor Stands
