### ISSUE TITLE
[Bug]: Aether Equipment not visible on posed armorstand

### ISSUE THREAD

**Issue by throbbingmoist** [Mrbysco/Armor-Poser#12]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Forge 47.2.17 / NeoForge 47.1.83

### Minecraft version

1.20.1

### Mod version

2.1.2

### Java version

Jdk 17.0.5.8

### Issue Description

On a server, Aether mod equipment does not display on a posed armor stand. This issue is not present in single-player. The equipment is visible in a single-player world. Can consistently recreate within multi-player.

**Comment by Mrbysco** [comment]
This is not related to Armor Poser, all the mod does is apply NBT to the vanilla armor stand. The armor stand rendering stays vanilla or another mod is changing it
