### ISSUE TITLE
Armor Stand pose shifts even if it shouldn't 

### ISSUE THREAD

**Issue by J4PC** [Mrbysco/Armor-Poser#15]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am using the latest version of the mod

### Loader version

fabric-loader-0.15.7-1.20.4 and later

### Minecraft version

1.20.4 and later

### Mod version

4.1.1 and later

### Java version

Java 8 Update 401

### Issue Description

**Steps to reproduce:**
1. Take an Armor Stand
(Optional) For better visuality but some armor on it
![image](https://github.com/Mrbysco/Armor-Poser/assets/97805057/354c554d-094f-4d31-8db7-dbb9fab7a779)
2. Change any setting (event the ones that don't modify the position, like "Name Visible")
![image](https://github.com/Mrbysco/Armor-Poser/assets/97805057/684396d9-fab1-4d60-97de-9968c2a98ab8)
3. Result: And the pose changes in a way you didn't input 
![image](https://github.com/Mrbysco/Armor-Poser/assets/97805057/b27d9b53-de94-4fbc-961d-9e8eef59ea1b)

**Comment by J4PC** [comment]
This is still present in the latest version "ArmorPoser-fabric-1.21-6.0.6

https://github.com/user-attachments/assets/250ac689-7bf6-49a3-8fd3-4690dc15c544

It affects all actions that can be done with the mod.

**Comment by Mrbysco** [comment]
Found the problem and fixed it
