### ISSUE TITLE
[Bug]: 1.20.5 client Disconnects from server when shift right clicking armor stand

### ISSUE THREAD

**Issue by Lemonszz** [Mrbysco/Armor-Poser#17]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Fabric 0.15.10

### Minecraft version

1.20.5

### Mod version

5.0.0

### Java version

OpenJDK 21

### Issue Description

Client disconnects when shift right clicking armor stand.

Both Client and server have 1.20.5-5.0.0. 
Server doesn't give any error.

Client log contains
```
Client disconnected with reason: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (armorposer:screen_packet)
```

No other errors on client or server side.

**Comment by Mrbysco** [comment]
Publishing a new build that hopefully fixes it

**Comment by Mrbysco** [comment]
Please check 5.0.1
