### ISSUE TITLE
[Bug]: "Swap main and off hand" button swaps head and main hand

### ISSUE THREAD

**Issue by Jadestrouble** [Mrbysco/Armor-Poser#19]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Loader version

0.15.11

### Minecraft version

1.21

### Mod version

6.0.1

### Java version

21.0.3

### Issue Description

The issue is what it says on the tin. Probably a honest mistake of mapping the button to the wrong action.

**Comment by Mrbysco** [comment]
A new version is being uploaded and will be available shortly
