### ISSUE TITLE
[Suggestion]: Ru lang

### ISSUE THREAD

**Issue by JustOldSchool** [Mrbysco/Armor-Poser#20]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [x] I would like to propose another thing

### Suggestion Description

Hello, plz add
[ru_ru.json](https://github.com/user-attachments/files/16128877/ru_ru.json)

**Comment by JustOldSchool** [comment]
For ArmorPoser-fabric-1.21-6.0.2

**Comment by Mrbysco** [comment]
I'll add it once I'm back from vacation at the start of next week

**Comment by JustOldSchool** [comment]
Can I send a new translation here?

**Comment by Mrbysco** [comment]
Sure

**Comment by JustOldSchool** [comment]
[ru_ru.json](https://github.com/user-attachments/files/16310197/ru_ru.json)
![image](https://github.com/user-attachments/assets/bb08d39e-8002-4181-95a6-c0683264765e)
I have translated everything, but all the tooltip in ModMenu is not show.

**Comment by Mrbysco** [comment]
Will look into that, probably forgot an annotation

**Comment by JustOldSchool** [comment]
![image](https://github.com/user-attachments/assets/51786b20-d48d-49aa-bd10-ef40f4c94ca1)
Everything is working. 6.0.6 ru_ru Ready
Thank you for your communicativeness.
[ru_ru.json](https://github.com/user-attachments/files/16416247/ru_ru.json)

**Comment by JustOldSchool** [comment]
[ru_ru.json](https://github.com/user-attachments/files/16500939/ru_ru.json)

new translation 6.0.7

**Comment by JustOldSchool** [comment]
ArmorPoser-fabric-1.21-6.1.0
[ru_ru.json](https://github.com/user-attachments/files/16729934/ru_ru.json)
