### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by duurk404** [Mrbysco/Armor-Poser#4]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

41.1.0

### Mod version

1.1.0

### Java version

?

### Issue Description

When ever I right click the armor stand it crashes my game.

### Additional Information

https://user-images.githubusercontent.com/111526156/185451093-b99ec992-720a-4057-8919-3ebbc763645d.mp4

**Comment by Mrbysco** [comment]
Update the mod, Version 1.2.0 has been up since July 25th and that version works on 1.19 (1.19.1 and 1.19.2 too)
