### ISSUE TITLE
[Bug]: I can't even open the GUI

### ISSUE THREAD

**Issue by RandomGuy91** [Mrbysco/Armor-Poser#6]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.2.0

### Minecraft version

1.18.2

### Mod version

1.0.4

### Java version

idk

### Issue Description

Whenever I shift click on the armor stand, nothing happens and there's absolutely nothing in the log. Are there any mods that would prevent the GUI from opening (eg. another mod that does something when you shift click on an armor stand)?

### Additional Information

As I said, no crash and there's nothing related in the log

**Comment by Mrbysco** [comment]
Are you sure you're shift right-clicking?
I'm unable to reproduce your problem

**Comment by RandomGuy91** [comment]
Here, I have a video and my modlist: (There's a lot of them) [https://pastebin.com/3uMSQwF0] [https://drive.google.com/file/d/13lzVicUN9CAdN9OI4hYxqGYeTjD1HkYv/view?usp=share_link]

**Comment by RandomGuy91** [comment]
Yes, I am definetly doing it correctly

**Comment by RandomGuy91** [comment]
Hi, just checking in. Do you have any idea what's going on?

**Comment by Mrbysco** [comment]
I got no clue why it wouldn't open, the only way would be for another mod to cancel the interaction event early

**Comment by RandomGuy91** [comment]
Ok, thx for trying :)
