### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PerimiumGamer** [Mrbysco/Armor-Poser#7]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Fabric

### Minecraft version

1.20.1

### Mod version

I don't know

### Java version

Java 17

### Issue Description

The mod doesn't work

**Comment by Mrbysco** [comment]
Duplicate
