### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PerimiumGamer** [Mrbysco/Armor-Poser#8]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Fabric

### Minecraft version

1.20.1

### Mod version

I don't know

### Java version

Java 17

### Issue Description

The mod doesn't work

### Additional Information

The mod won't let me customize the armor stands

**Comment by Mrbysco** [comment]
Do you have the mod installed on both the client and the server? And is the fabric api installed on both?

**Comment by PerimiumGamer** [comment]
Hello,
yes I do have it installed on client and on server

**Comment by Mrbysco** [comment]
Are you shift right-clicking it with an empty hand?

**Comment by PerimiumGamer** [comment]
Sorry for not responding till now but yes I am shift clicking it

**Comment by Mrbysco** [comment]
Then I have no idea, as I installed a fresh fabric server with just Armor Poser, Cloth Config and the Fabric API installed and it worked just fine for me
